"""
Property schemes configuration for the GameBus data analyzer.
This file contains property schemes extracted from the HW8-database-bootstrap.xlsx file.
"""

# Dictionary mapping activity schemes to their property schemes
ACTIVITY_TO_PROPERTIES = {'AROUSAL': ['LIKERT_SCALE_THREE'],
 'BIKE': ['DESCRIPTION', 'DISTANCE', 'DURATION', 'KCALORIES', 'SECRET', 'SPEED.AVG', 'VIDEO', 'EMOTION_AFTER_ACTIVITY'],
 'BIKE_PERFORMANCE': ['SECRET',
                      'DURATION',
                      'BIKE_PERFORMANCE_BASELINE',
                      'BIKE_PERFORMANCE_GOAL',
                      'BIKE_PERFORMANCE_GROW'],
 'BODY_MASS_INDEX': ['SECRET',
                     'DURATION',
                     'AGE',
                     'BODY_MASS_INDEX',
                     'GENDER',
                     'LENGTH',
                     'WAIST_CIRCUMFERENCE',
                     'WEIGHT'],
 'BODY_MOVEMENT': ['DUTCH_POLICE_MOVES', 'LIKERT_SCALE_THREE'],
 'CONSENT': ['DESCRIPTION', 'FOR_CAMPAIGN'],
 'DAY_AGGREGATE': ['CONFIGURATION_NAME',
                   'START_DATE',
                   'END_DATE',
                   'STEPS_SUM',
                   'STEPS_AVG',
                   'STEPS_MAX',
                   'DISTANCE_SUM',
                   'DISTANCE_AVG',
                   'DISTANCE_MAX',
                   'DEVICE_TYPE'],
 'DAY_AGGREGATE_RUN': ['SECRET',
                       'DESCRIPTION',
                       'CONFIGURATION_NAME',
                       'START_DATE',
                       'END_DATE',
                       'STEPS_SUM',
                       'STEPS_AVG',
                       'STEPS_MAX',
                       'DISTANCE_SUM',
                       'DISTANCE_AVG',
                       'DISTANCE_MAX',
                       'VIDEO'],
 'DAY_AGGREGATE_WALK': ['SECRET',
                        'DESCRIPTION',
                        'CONFIGURATION_NAME',
                        'START_DATE',
                        'END_DATE',
                        'STEPS_SUM',
                        'STEPS_AVG',
                        'STEPS_MAX',
                        'DISTANCE_SUM',
                        'DISTANCE_AVG',
                        'DISTANCE_MAX',
                        'VIDEO'],
 'DO_LATER': ['LIKERT_SCALE_SEVEN'],
 'DRINKING_DIARY': ['SECRET', 'DESCRIPTION', 'RANGE_GLASS_ALC', 'RANGE_GLASS_SUGAR', 'VIDEO'],
 'ELDERLY_ACTIVITY': ['CONTEXT', 'SPEED.AVG'],
 'EMOTION_SCALE_FIVE': ['LIKERT_SCALE_FIVE'],
 'GENERAL_ACTIVITY': ['ACTIVITY_TYPE',
                      'SECRET',
                      'DESCRIPTION',
                      'DURATION',
                      'STEPS',
                      'STEPS_SUM',
                      'VIDEO',
                      'EMOTION_AFTER_ACTIVITY'],
 'GENERAL_SURVEY': ['SECRET', 'DESCRIPTION', 'GENERAL_SURVEY_ANSWER'],
 'H5P_GENERAL': ['SECRET',
                 'DESCRIPTION',
                 'DURATION',
                 'ACTIVITY_TYPE',
                 'MIN_SCORE',
                 'MAX_SCORE',
                 'SCORE',
                 'SCORE_RATIO'],
 'HOW_ACTIVE_DO_YOU_FEEL_AT_THE_MOMENT': ['LIKERT_SCALE_FIVE'],
 'LOCATION': ['SECRET', 'DESCRIPTION', 'DURATION', 'COORDINATES', 'JSON.GEO', 'VIDEO'],
 'LOCATION_FAMILIARITY': ['LIKERT_SCALE_FIVE'],
 'LOG_AWARENESS': ['HEARTBEAT', 'LIGHT', 'MEETING', 'SMELL', 'SOUND', 'TASTE', 'TOUCH'],
 'LOG_MOOD': ['AROUSAL_STATE_VALUE',
              'EVENT_AREA',
              'EVENT_TIMESTAMP',
              'INTOXICATION_LEVEL',
              'PANAS_AFFECTIVE_EMOTIONAL_STATE_KEY',
              'PANAS_AFFECTIVE_EMOTIONAL_STATE_VALUE',
              'TRAFFIC_LIGHT_VALUE',
              'VALENCE_STATE_VALUE'],
 'MIPIP': ['SECRET',
           'DURATION',
           'MIPIP_AGREE_Q01',
           'MIPIP_AGREE_Q02',
           'MIPIP_AGREE_Q03',
           'MIPIP_AGREE_Q04',
           'MIPIP_AGREEABLENESS',
           'MIPIP_CONSC_Q01',
           'MIPIP_CONSC_Q02',
           'MIPIP_CONSC_Q03',
           'MIPIP_CONSC_Q04',
           'MIPIP_CONSCIENTIOUSNESS',
           'MIPIP_EXTRA_Q01',
           'MIPIP_EXTRA_Q02',
           'MIPIP_EXTRA_Q03',
           'MIPIP_EXTRA_Q04',
           'MIPIP_EXTRAVERSION',
           'MIPIP_INTEL_Q01',
           'MIPIP_INTEL_Q02',
           'MIPIP_INTEL_Q03',
           'MIPIP_INTEL_Q04',
           'MIPIP_INTELLECT',
           'MIPIP_NEURO_Q01',
           'MIPIP_NEURO_Q02',
           'MIPIP_NEURO_Q03',
           'MIPIP_NEURO_Q04',
           'MIPIP_NEUROTICISM'],
 'NAVIGATE_APP': ['APP', 'FOR_CAMPAIGN', 'SESSION', 'UID', 'URI'],
 'NOTIFICATION(DETAIL)': ['ACTION', 'EVENT_TIMESTAMP'],
 'NUTRITION_DIARY': ['SECRET',
                     'DESCRIPTION',
                     'MEAL_TYPE',
                     'FIBERS_WEIGHT',
                     'KCAL_CARB',
                     'KCAL_FATS',
                     'KCAL_PROTEINS',
                     'PERC_CARB',
                     'PERC_FATS',
                     'PERC_FIBERS',
                     'PERC_PROTEINS',
                     'VIDEO'],
 'NUTRITION_DIARY_VID': ['DESCRIPTION',
                         'IS_COMPLIANT',
                         'REF_TO_MEAL_PLAN',
                         'MEAL_TOTAL_WEIGHT_ESTIMATED_G',
                         'MEAL_CARB_WEIGHT_ESTIMATED_G',
                         'VIDEO'],
 'NUTRITION_SUMMARY': ['AGGREGATION_LEVEL',
                       'SUMMARY_SCORE',
                       'CARBS_CONFORMANCE',
                       'FAT_CONFORMANCE',
                       'FIBER_CONFORMANCE'],
 'PEOPLE_COMPANY': ['LIKERT_SCALE_SIX'],
 'PHYSICAL_ACTIVITY': ['SECRET', 'DESCRIPTION', 'DURATION', 'PA_INTENSITY', 'SPORTS', 'VIDEO'],
 'PLAN_MEAL': ['NR_DAYS', 'NR_MEALS', 'MEAL_PLAN_JS'],
 'PLAY_LOTTERY': ['LOTTERY', 'FOR_CHALLENGE', 'WIN', 'REWARD'],
 'RECENTLY_COLD_BEVERAGE': ['LIKERT_SCALE_THREE'],
 'RECENTLY_EATEN': ['LIKERT_SCALE_FOUR'],
 'RUN': ['DESCRIPTION',
         'DISTANCE',
         'DURATION',
         'KCALORIES',
         'SECRET',
         'SPEED.AVG',
         'SPEED.MAX',
         'STEPS',
         'VIDEO',
         'EMOTION_AFTER_ACTIVITY'],
 'SCORE_GAMEBUS_POINTS': ['ACTIVITY', 'FOR_CHALLENGE', 'CHALLENGE_RULE', 'NUMBER_OF_POINTS'],
 'SOCIAL_SELFIE': ['SECRET', 'DESCRIPTION', 'DURATION', 'GROUP_SIZE', 'COORDINATES', 'JSON.GEO', 'VIDEO'],
 'SPORTS_PERFORMANCE': ['SECRET',
                        'DURATION',
                        'SPORTS_PERFORMANCE_BASELINE',
                        'SPORTS_PERFORMANCE_GOAL',
                        'SPORTS_PERFORMANCE_GROW'],
 'SUBJECTIVE_EMOTION': ['LIKERT_SCALE_TEN'],
 'SUBJECTIVE_MOOD': ['LIKERT_SCALE_TEN'],
 'TIZEN(DETAIL)': ['ACCELEROMETER_LOG', 'ACTIVITY_TYPE', 'HRM_LOG', 'PPG_LOG'],
 'TIZEN_LOG(DETAIL)': ['TIZEN_LOG_PAYLOAD'],
 'TRANSPORT': ['ALTITUDE.AVG',
               'ALTITUDE.MAX',
               'ALTITUDE.MIN',
               'DESCRIPTION',
               'DISTANCE',
               'DURATION',
               'JSONARRAY.GEO',
               'SECRET',
               'SPEED.AVG',
               'SPEED.MAX',
               'VIDEO'],
 'VALENCE': ['LIKERT_SCALE_THREE'],
 'VISIT_APP_PAGE': ['APP_NAME', 'PAGE_NAME', 'DURATION_MS'],
 'WALK': ['DESCRIPTION',
          'DISTANCE',
          'DURATION',
          'KCALORIES',
          'SECRET',
          'SPEED.AVG',
          'SPEED.MAX',
          'STEPS',
          'VIDEO',
          'EMOTION_AFTER_ACTIVITY'],
 'WALK_PERFORMANCE': ['SECRET',
                      'DURATION',
                      'WALK_PERFORMANCE_BASELINE',
                      'WALK_PERFORMANCE_GOAL',
                      'WALK_PERFORMANCE_GROW']}

# Dictionary mapping property names to their details (type, unit, etc.)
PROPERTY_DETAILS = {'ACCELEROMETER_LOG': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'ACCELEROMETER DUMP', 'values': None},
 'ACTION': {'input_as': 'STRING', 'type': 'INT', 'unit': 'String text', 'values': None},
 'ACTIVITY': {'input_as': 'GAMESESSION', 'type': 'ACTIVITY', 'unit': 'ID', 'values': None},
 'ACTIVITY_TYPE': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'String', 'values': None},
 'AGE': {'input_as': 'INT', 'type': 'INT', 'unit': '[0 - 99]', 'values': None},
 'AGGREGATION_LEVEL': {'input_as': 'STRING',
                       'type': 'STRING',
                       'unit': 'DAILY | WEEKLY | MONTHLY',
                       'values': '[DAILY, DAILY], [WEEKLY, WEEKLY], [MONTHLY, MONTHLY]'},
 'ALTITUDE.AVG': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'meters', 'values': None},
 'ALTITUDE.MAX': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'meters', 'values': None},
 'ALTITUDE.MIN': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'meters', 'values': None},
 'APP': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'string', 'values': None},
 'APP_NAME': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'string', 'values': None},
 'AROUSAL_STATE_VALUE': {'input_as': 'INT', 'type': 'INT', 'unit': '[1 .. 9]', 'values': None},
 'BIKE_PERFORMANCE_BASELINE': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Survey answer', 'values': None},
 'BIKE_PERFORMANCE_GOAL': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Survey answer', 'values': None},
 'BIKE_PERFORMANCE_GROW': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Survey answer', 'values': None},
 'BODY_MASS_INDEX': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'kg/m2', 'values': None},
 'CARBS_CONFORMANCE': {'input_as': 'INT', 'type': 'INT', 'unit': '[0 - ...]', 'values': None},
 'CHALLENGE_RULE': {'input_as': 'RULE', 'type': 'CHALLENGE_RULE', 'unit': 'ID', 'values': None},
 'CONFIGURATION_NAME': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'String text', 'values': None},
 'CONTEXT': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'STRING', 'values': None},
 'COORDINATES': {'input_as': 'COORDINATE', 'type': 'COORDINATE', 'unit': '(latitude,longitude)', 'values': None},
 'DESCRIPTION': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'String text', 'values': None},
 'DEVICE_TYPE': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'GARMIN | TIZEN | WEAROS', 'values': None},
 'DISTANCE': {'input_as': 'DISTANCE', 'type': 'DOUBLE', 'unit': 'meters', 'values': None},
 'DISTANCE_AVG': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'double', 'values': None},
 'DISTANCE_MAX': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'double', 'values': None},
 'DISTANCE_SUM': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'double', 'values': None},
 'DURATION': {'input_as': 'INT', 'type': 'DOUBLE', 'unit': 'seconds', 'values': None},
 'DURATION_MS': {'input_as': 'INT', 'type': 'INT', 'unit': 'milliseconds', 'values': None},
 'DUTCH_POLICE_MOVES': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'STRING', 'values': None},
 'EMOTION_AFTER_ACTIVITY': {'input_as': 'ENUM',
                            'type': 'STRING',
                            'unit': 'SAD | ANGRY | FEAR | SURPRISE | DISGUST | HAPPY',
                            'values': '[SAD, SAD], [ANGRY, ANGRY], [FEAR, FEAR], [SURPRISE, SURPRISE], [DISGUST, '
                                      'DISGUST], [HAPPY, HAPPY]'},
 'END_DATE': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Date', 'values': None},
 'EVENT_AREA': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'EVENT AREA', 'values': None},
 'EVENT_TIMESTAMP': {'input_as': 'INT', 'type': 'STRING', 'unit': 'Milliseconds', 'values': None},
 'FAT_CONFORMANCE': {'input_as': 'INT', 'type': 'INT', 'unit': '[0 - ...]', 'values': None},
 'FIBERS_WEIGHT': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'grams', 'values': None},
 'FIBER_CONFORMANCE': {'input_as': 'INT', 'type': 'INT', 'unit': '[0 - ...]', 'values': None},
 'FOR_CAMPAIGN': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Campaign abbreviation', 'values': None},
 'FOR_CHALLENGE': {'input_as': 'CHALLENGE', 'type': 'CHALLENGE', 'unit': 'ID', 'values': None},
 'GENDER': {'input_as': 'STRING', 'type': 'STRING', 'unit': '{ male, female, alt }', 'values': None},
 'GENERAL_SURVEY_ANSWER': {'input_as': 'JSON',
                           'type': 'STRING',
                           'unit': '{ "index": "number", "question": "string", "answer": "string" }',
                           'values': None},
 'GROUP_SIZE': {'input_as': 'INT', 'type': 'INT', 'unit': '[0 - inf]', 'values': None},
 'HEARTBEAT': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'HRM_LOG': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'HRM DUMP', 'values': None},
 'INTOXICATION_LEVEL': {'input_as': 'INT', 'type': 'INT', 'unit': 'INTOXICATION LEVEL', 'values': None},
 'IS_COMPLIANT': {'input_as': 'BOOL', 'type': 'BOOL', 'unit': '0 | 1 | FALSE | TRUE', 'values': None},
 'JSON.GEO': {'input_as': 'JSON', 'type': 'STRING', 'unit': '{ "key": "value" }', 'values': None},
 'JSONARRAY.GEO': {'input_as': 'JSONARRAY', 'type': 'STRING', 'unit': '[{ "key": "value" }]', 'values': None},
 'KCALORIES': {'input_as': 'INT', 'type': 'INT', 'unit': 'kilo calories', 'values': None},
 'KCAL_CARB': {'input_as': 'INT', 'type': 'INT', 'unit': 'kilo calories', 'values': None},
 'KCAL_FATS': {'input_as': 'INT', 'type': 'DOUBLE', 'unit': 'kilo calories', 'values': None},
 'KCAL_PROTEINS': {'input_as': 'INT', 'type': 'INT', 'unit': 'kilo calories', 'values': None},
 'LENGTH': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'centimeters', 'values': None},
 'LIGHT': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'LIKERT_SCALE_FIVE': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'LIKERT_SCALE_FOUR': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'LIKERT_SCALE_SEVEN': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'LIKERT_SCALE_SIX': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'LIKERT_SCALE_TEN': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'LIKERT_SCALE_THREE': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'LOTTERY': {'input_as': 'LOTTERY', 'type': 'LOTTERY', 'unit': 'ID', 'values': None},
 'MAX_SCORE': {'input_as': 'INT', 'type': 'INT', 'unit': 'Integer', 'values': None},
 'MEAL_CARB_WEIGHT_ESTIMATED_G': {'input_as': 'INT', 'type': 'INT', 'unit': 'grams', 'values': None},
 'MEAL_PLAN_JS': {'input_as': 'STRING', 'type': 'STRING', 'unit': '{ "key": "value" }', 'values': None},
 'MEAL_TOTAL_WEIGHT_ESTIMATED_G': {'input_as': 'INT', 'type': 'INT', 'unit': 'grams', 'values': None},
 'MEAL_TYPE': {'input_as': 'STRING', 'type': 'STRING', 'unit': '[allowed value]', 'values': None},
 'MEETING': {'input_as': 'STRING', 'type': 'INT', 'unit': 'STRING', 'values': None},
 'MIN_SCORE': {'input_as': 'INT', 'type': 'INT', 'unit': 'Integer', 'values': None},
 'MIPIP_AGREEABLENESS': {'input_as': 'HIDDEN', 'type': 'DOUBLE', 'unit': '[1, 5]', 'values': None},
 'MIPIP_AGREE_Q01': {'input_as': 'LIKERT-5',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_AGREE_Q02': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_AGREE_Q03': {'input_as': 'LIKERT-5',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_AGREE_Q04': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_CONSCIENTIOUSNESS': {'input_as': 'HIDDEN', 'type': 'DOUBLE', 'unit': '[1, 5]', 'values': None},
 'MIPIP_CONSC_Q01': {'input_as': 'LIKERT-5',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_CONSC_Q02': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_CONSC_Q03': {'input_as': 'LIKERT-5',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_CONSC_Q04': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_EXTRAVERSION': {'input_as': 'HIDDEN', 'type': 'DOUBLE', 'unit': '[1, 5]', 'values': None},
 'MIPIP_EXTRA_Q01': {'input_as': 'LIKERT-5',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_EXTRA_Q02': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_EXTRA_Q03': {'input_as': 'LIKERT-5',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_EXTRA_Q04': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_INTELLECT': {'input_as': 'HIDDEN', 'type': 'DOUBLE', 'unit': '[1, 5]', 'values': None},
 'MIPIP_INTEL_Q01': {'input_as': 'LIKERT-5',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_INTEL_Q02': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_INTEL_Q03': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_INTEL_Q04': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_NEUROTICISM': {'input_as': 'HIDDEN', 'type': 'DOUBLE', 'unit': '[1, 5]', 'values': None},
 'MIPIP_NEURO_Q01': {'input_as': 'LIKERT-5',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_NEURO_Q02': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_NEURO_Q03': {'input_as': 'LIKERT-5',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'MIPIP_NEURO_Q04': {'input_as': 'LIKERT-5-REVERSE',
                     'type': 'INT',
                     'unit': '[1, 5]',
                     'values': '[1, STRONGLY_DISAGREE], [2, DISAGREE], [3, NEUTRAL], [4, AGREE], [5, STRONGLY_AGREE]'},
 'NR_DAYS': {'input_as': 'INT', 'type': 'INT', 'unit': '[0 - ...]', 'values': None},
 'NR_MEALS': {'input_as': 'INT', 'type': 'INT', 'unit': '[0 - ...]', 'values': None},
 'NUMBER_OF_POINTS': {'input_as': 'INT', 'type': 'NUMBER_OF_POINTS', 'unit': 'count', 'values': None},
 'PAGE_NAME': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'string', 'values': None},
 'PANAS_AFFECTIVE_EMOTIONAL_STATE_KEY': {'input_as': 'INT', 'type': 'INT', 'unit': '[1 .. 20]', 'values': None},
 'PANAS_AFFECTIVE_EMOTIONAL_STATE_VALUE': {'input_as': 'INT', 'type': 'INT', 'unit': '[1, 2, 3, 4, 5]', 'values': None},
 'PA_INTENSITY': {'input_as': 'INT', 'type': 'INT', 'unit': '[0 - 3]', 'values': None},
 'PERC_CARB': {'input_as': 'PERCENTAGE', 'type': 'DOUBLE', 'unit': '%', 'values': None},
 'PERC_FATS': {'input_as': 'PERCENTAGE', 'type': 'DOUBLE', 'unit': '%', 'values': None},
 'PERC_FIBERS': {'input_as': 'PERCENTAGE', 'type': 'DOUBLE', 'unit': '%', 'values': None},
 'PERC_PROTEINS': {'input_as': 'PERCENTAGE', 'type': 'DOUBLE', 'unit': '%', 'values': None},
 'PPG_LOG': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'PPG DUMP', 'values': None},
 'RANGE_GLASS_ALC': {'input_as': 'INT', 'type': 'INT', 'unit': '[0, 1-5, 6-10, 11-15, 16-20, 20+]', 'values': None},
 'RANGE_GLASS_SUGAR': {'input_as': 'INT', 'type': 'INT', 'unit': '[0, 1-5, 6-10, 11-15, 16-20, 20+]', 'values': None},
 'REF_TO_MEAL_PLAN': {'input_as': 'ACTIVITY', 'type': 'ACTIVITY', 'unit': 'reference to a meal plan', 'values': None},
 'REWARD': {'input_as': 'STRING', 'type': 'REWARD', 'unit': 'String text', 'values': None},
 'SCORE': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': '[-inf, inf]', 'values': None},
 'SCORE_RATIO': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'Double', 'values': None},
 'SECRET': {'input_as': 'HIDDEN', 'type': 'STRING', 'unit': 'string', 'values': None},
 'SESSION': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'string', 'values': None},
 'SMELL': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'SOUND': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'SPEED.AVG': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'meters / second', 'values': None},
 'SPEED.MAX': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'meters / second', 'values': None},
 'SPORTS': {'input_as': 'STRING',
            'type': 'STRING',
            'unit': 'One of enum value',
            'values': '[AEROBICS, AEROBICS], [ATHLETICS, ATHLETICS], [BADMINTON, BADMINTON], [BASEBALL, BASEBALL], '
                      '[BASKETBALL, BASKETBALL], [DANCE, DANCE], [FIELD_HOCKEY, FIELD_HOCKEY], [FITNESS, FITNESS], '
                      '[GOLF, GOLF], [GYMNASTICS, GYMNASTICS], [HIKE, HIKE], [HORSE_RIDING, HORSE_RIDING], '
                      '[ICE_HOCKEY, ICE_HOCKEY], [ICE_SKATING, ICE_SKATING], [LACROSSE, LACROSSE], [MARTIAL_ARTS, '
                      'MARTIAL_ARTS], [MOUNTAINBIKE, MOUNTAINBIKE], [ROLLER_SKATING, ROLLER_SKATING], [RUGBY, RUGBY], '
                      '[SKIING, SKIING], [SOCCER, SOCCER], [SQUASH, SQUASH], [SURFING, SURFING], [SWIMMING, SWIMMING], '
                      '[TABLE_TENNIS, TABLE_TENNIS], [TENNIS, TENNIS], [VOLLEYBALL, VOLLEYBALL], [WATER_POLO, '
                      'WATER_POLO], [YOGA, YOGA], [OTHER, OTHER]'},
 'SPORTS_PERFORMANCE_BASELINE': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Survey answer', 'values': None},
 'SPORTS_PERFORMANCE_GOAL': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Survey answer', 'values': None},
 'SPORTS_PERFORMANCE_GROW': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Survey answer', 'values': None},
 'START_DATE': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Date', 'values': None},
 'STEPS': {'input_as': 'INT', 'type': 'INT', 'unit': 'count', 'values': None},
 'STEPS_AVG': {'input_as': 'INT', 'type': 'INT', 'unit': 'integer', 'values': None},
 'STEPS_MAX': {'input_as': 'INT', 'type': 'INT', 'unit': 'integer', 'values': None},
 'STEPS_SUM': {'input_as': 'INT', 'type': 'INT', 'unit': 'integer', 'values': None},
 'SUMMARY_SCORE': {'input_as': 'INT', 'type': 'INT', 'unit': '[0 - 100]', 'values': None},
 'TASTE': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'TIZEN_LOG_PAYLOAD': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'String text', 'values': None},
 'TOUCH': {'input_as': 'INT', 'type': 'INT', 'unit': 'INT', 'values': None},
 'TRAFFIC_LIGHT_VALUE': {'input_as': 'STRING', 'type': 'INT', 'unit': '[green,yellow,orange,red]', 'values': None},
 'UID': {'input_as': 'INT', 'type': 'INT', 'unit': 'User ID', 'values': None},
 'URI': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'string', 'values': None},
 'VALENCE_STATE_VALUE': {'input_as': 'INT', 'type': 'INT', 'unit': '[1 .. 9]', 'values': None},
 'VIDEO': {'input_as': 'VIDEO', 'type': 'STRING', 'unit': 'video uri', 'values': None},
 'WAIST_CIRCUMFERENCE': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'centimeters', 'values': None},
 'WALK_PERFORMANCE_BASELINE': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Survey answer', 'values': None},
 'WALK_PERFORMANCE_GOAL': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Survey answer', 'values': None},
 'WALK_PERFORMANCE_GROW': {'input_as': 'STRING', 'type': 'STRING', 'unit': 'Survey answer', 'values': None},
 'WEIGHT': {'input_as': 'DOUBLE', 'type': 'DOUBLE', 'unit': 'kGrams', 'values': None},
 'WIN': {'input_as': 'BOOL', 'type': 'BOOL', 'unit': '0 | 1 | FALSE | TRUE', 'values': None}}
